# Generated by Django 2.2.2 on 2019-06-11 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190611_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='aboout',
            new_name='about',
        ),
    ]
