# Generated by Django 2.2.2 on 2019-06-11 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190611_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='about',
            new_name='aboout',
        ),
    ]
