# Generated by Django 2.2.2 on 2019-06-11 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190611_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='aboout',
            new_name='about',
        ),
    ]
